### ISSUE TITLE
No subscriptions anymore

### ISSUE THREAD

**Issue by ivoruetsche** [azzy9/plugin.video.rumble#16] opened 2023-11-15 21:38 UTC
Hi

Since some days I didn't have the subscriptions list anymore available, just the ".." to the parent folder.

Is it only me with this problem?

Ivo

**Comment by azzy9** [comment] 2023-11-15 23:08
Thank you for your report, it should now be fixed in v1.4.13

**Closed by azzy9** 2023-11-15 23:08 UTC

**Comment by ivoruetsche** [comment] 2023-11-16 00:08
Thanks a lot, great job :-)

**Comment by ivoruetsche** [comment] 2023-11-17 13:46
Hi

Is it possible, that now are only users (https://rumble.com/user/) listed, but not channels (https://rumble.com/c/)?

Ivo

**Comment by azzy9** [comment] 2023-11-17 13:54
Hi, I am unsure what is being asked? The subscriptions gets videos from your subscribed channels and users. This plugin does none of the sorting, but simply gets the feed from the page [https://rumble.com/subscriptions](https://rumble.com/subscriptions)

**Comment by ivoruetsche** [comment] 2023-11-17 14:02
On https://rumble.com/subscriptions I see all my subscriptions, that's true. There are some subscribers, where the url starts with "https://rumble.com/c/" (channels) and others with "https://rumble.com/user/" (users). At the moment I can see only the users in the kodi plugin.

**Comment by azzy9** [comment] 2023-11-17 14:15
Unfortunately I cannot replicate this issue. All that I am subscribed to are channels, I had to subscribe to a user to make sure it picked up both. Is there any Channel You can suggest for me to test.
Also to note it will not show live videos in the subscriptions

**Comment by ivoruetsche** [comment] 2023-11-17 14:22
For example, this one https://rumble.com/c/SC360Media

**Comment by azzy9** [comment] 2023-11-17 14:28
I can confirm the issue, It is due to the channel having no image for it's avatar, so using a letter instead. I will need to change the REGEX to take this into account

**Comment by ivoruetsche** [comment] 2023-11-17 14:53
Ah okay, yes, this is also on my other channels where are not listed. Thanks a lot

**Comment by azzy9** [comment] 2023-11-17 15:10
Should be fixed in commit: https://github.com/azzy9/plugin.video.rumble/commit/84c57c588b5ac7b3d50caee2aa378701f7533255
I just need to test and push the update which I shall do when I get home.

**Comment by azzy9** [comment] 2023-11-17 18:06
v1.4.14 released

**Comment by ivoruetsche** [comment] 2023-11-24 07:12
Thank you for the 1.4.15 release, but it looks, that the fix from 1.4.14 is not included or no longer working?

**Comment by azzy9** [comment] 2023-11-24 09:46
I had to change the REGEX completely in 1.4.15 as the HTML changed on rumble. this is an issue with scraping in general. I will look into it when I get a chance.

**Comment by azzy9** [comment] 2023-11-25 15:44
@ivoruetsche issue should now be fixed in v1.4.16
