### ISSUE TITLE
Logged in Favoritres, Subscriptions, Following

### ISSUE THREAD

**Issue by NipponBill** [azzy9/plugin.video.rumble#19] opened 2023-12-26 04:35 UTC
I started using the plugin from version [plugin.video.rumble-1.4.17](https://github.com/azzy9/plugin.video.rumble/releases/tag/v1.4.17). The behavior persists with [plugin.video.rumble-1.4.18](https://github.com/azzy9/plugin.video.rumble/releases/tag/1.4.18)

When initially testing the plugin (1.4.17) I manually added a few Favorites to test. It seemed to work well, so I logged in to an existing account. 

The **Favorites** remain the same as what I entered manually. None of the Favorites from the logged in account are reflected. **Reset session** in the **Settings** does nothing to affect this.

The **Subscriptions** remain empty whether logged in or not logged in.

The **Following** list contains a bunch of accounts that I never followed, either in the test or on the signed in account.

I'm using a fresh install of LibreElec 11.03 with Kodi 20.2

**Comment by neo-neo1** [comment] 2023-12-26 10:07
I can confirm "Subscription" menu doesn't work. Haven't tested other menus as that's my main usage.

**Comment by NipponBill** [comment] 2023-12-26 14:11
I installed **1.4.18** about 15 minutes after it was released. That's the version I'm having the problems with now.

**Comment by azzy9** [comment] 2023-12-26 22:20
Unfortunately, I am unable to replicate this issue, which means it will be harder to solve.

Does the issue persist if you roll back to v1.4.17?
The only change to v1.4.18 is the subscriptions tab and the category videos e.g. news.
in v1.4.18 does the news page have a decent amount of results?

When you state "_The Following list contains a bunch of accounts that I never followed_", to me this sounds like a session issue.
The following tab gets the following from the left nav, when not logged in it shows random suggestions which it gets when there is an issue with your session.

Also favorites is stored in a file in kodi, and this functionality doesn't change even when logged in.

**Comment by NipponBill** [comment] 2023-12-27 00:23
I fully uninstalled v1.4.18, requested that all data be deleted during the uninstall, then did a full system reboot of LibreElec to confirm that the Rumble addon was gone.

I did a full reinstall of v1.4.18, and set the username and password before opening the app.

**Favorites** generates a modal dialog box saying that there are no Favorites.

**Subscriptions** is blank (just .. two dots) as before.

**Following** is populated by the same random list of users as before.

**News** and the other categories are all populated with a good number of listings. The categories displayed do not match what I've selected on the Rumbles account to be visible, but that's OK. The problem seems to be that the user session is not connecting correctly.

Is there perhaps a limit to the number of characters in the password field? This particular account probably as about 50 characters in the password.

How can I check whether the user session is properly connected? The only Rumble related errors I seen in the log are related to the inability to get FanArt images.

**Comment by azzy9** [comment] 2023-12-27 01:12
@NipponBill, I can now confirm this issue.
I created another profile with a rather long password and then subscribed to some channels. I then Logged in via the plugin and got the same result as you.
Probing the requests, the issue seems to be when the password gets to a certain length, the hashes generated for the password become incorrect.
Things for me to do: Fix the hash for the password (Don't know how long this will take as it could be an issue with how python handles integers instead of JavaScript, from which I converted the hash class from), inform the user when the site thinks the details are incorrect

**Comment by NipponBill** [comment] 2023-12-27 01:26
@azzy9 I'm glad we could narrow down the issue.

Do you know the number of characters that will work in the password field? I could generate a shorter one to work around this for now.

**Comment by azzy9** [comment] 2023-12-27 02:06
I have done some tests, it is caused by the hashStretch method, I generated a list of hashes in the browser using a loop, and compared them with what the plugin is generating, the hashes become different after 23 characters. so a password that is 23 characters or smaller should work.

**Comment by NipponBill** [comment] 2023-12-27 05:02
@azzy9 Thanks! I can confirm that a 23 character password does work!  I had been testing increasingly shorter passwords, but I still wasn't there at 26 characters and was about to go super-short before posting again.

With a 23 character password, I can log in a user session with v1.4.18!!

**Favorites** generates a modal dialog box saying that there are no Favorites. (expected)

**Subscriptions** contains a list of videos from channels that the account is subscribed to.

**Following** contains the list of channels that are followed by this particular user.

The remaining sections, News, Viral, Vlogs, etc. are populated, but they do not appear to correspond to the same videos on the Rumble.com site. I couldn't find a list that matched exactly. 

Regardless, I'm quite happy that I am able to log in to an existing Rumble account with the plugin. Thanks for your assistance.

I hope that the password field can be expanded without too much difficulty.

**Comment by azzy9** [comment] 2023-12-28 16:06
Hi @NipponBill,

please could you try v1.5.0.
I have tried with the alt/fake account with a password that is 50+ characters and it was working fine.
I have also added a login test in the settings, but requires the login details to be saved first to work otherwise will use what is previously saved.

This issue I have found is due to me giving the wrong order of a bitshift in the md5ex class.
Considering I converted it from JS to python, I am amazed that is the only issue that has emerged.

**Comment by NipponBill** [comment] 2023-12-28 23:37
@azzy9  I updated to v1.5.0 from v1.4.18 (rather than uninstalling and starting over). I can report that it works as you described.

I started with the logged in account using a 23 character password. I changed the account's password to 50+ characters, and used the **login test**. The plugin immediately signed in with the new account details.

Account content such as **Subscriptions** and **Following** still match the signed-in account.

**Comment by azzy9** [comment] 2023-12-28 23:56
Awesome to hear, I shall close this issue

**Closed by azzy9** 2023-12-28 23:56 UTC
Labels: bug

**Comment by NipponBill** [comment] 2023-12-29 00:06
Testing **v1.5.1** 
It seems to work as well. Only change I see is the formatting in the **Subscriptions** list.

Thanks for your help addressing this issue @azzy9

**Comment by azzy9** [comment] 2023-12-29 00:09
No problem, V1.5.1 just fixed some things
change log:
- re-add channel names into category videos
- Fix regex for following without image icon
- expand clean text method
- Apply clean text method to cat_video
