### ISSUE TITLE
Error when clicking on Crowder, 

### ISSUE THREAD

**Issue by techzilla** [azzy9/plugin.video.rumble#8] opened 2023-05-09 03:28 UTC
Other channels work that I've tried, but when clicking on Crowder's channel from following, it produces an error. 

https://rumble.com/c/StevenCrowder

**Comment by azzy9** [comment] 2023-05-09 12:14
Hi, unfortunately I cannot replicate this issue.
I have tried it from search & my follow list.
Please could you try to unfollow then follow again see if that changes anything.
If not, could you please send me a log.

**Comment by techzilla** [comment] 2023-05-19 16:36
https://paste.kodi.tv/amoviqubox

**Comment by azzy9** [comment] 2023-05-19 21:53
Thank you @techzilla for posting your log.
I can confirm it is due to how kodi is handleing the unicode characters that steven croders videos have in the title.
I isntalled Kodi 18.9 32bit but still couldn't replicate it.
Instead I took an approach to just remove the unicode characters from titles.
Please can you try v1.3.4 to see if it fixes your issue.

**Comment by azzy9** [comment] 2023-06-15 13:02
Since there is no feedback I will close this issue

**Closed by azzy9** 2023-06-15 13:02 UTC
Labels: requires feedback
